site_name: Справочники
site_url: https://xsltdev.ru/
site_description: Справочники web-разработчика
site_author: Бондаренко Юрий
copyright: (С) 2012-2019, Справочники web-разработчика

repo_name: 'Репозиторий сайта'
repo_url: 'https://github.com/bndby/xsltdev'

theme:
    name: 'material'
    palette:
        primary: 'green'
        accent: 'green'
    language: 'ru'
    favicon: 'assets/images/favicon.ico'
    feature:
        tabs: true

extra:
    social:
        - type: 'github'
          link: 'https://github.com/bndby'
        - type: 'linkedin'
          link: 'https://www.linkedin.com/in/bndby/'
    search:
        language: 'en, ru'

# google_analytics:
#   - 'UA-XXXXXXXX-X'
#   - 'auto'

markdown_extensions:
    - admonition
    - codehilite:
          guess_lang: false
          linenums: true
    - toc:
          permalink: true
    - pymdownx.extra
    - pymdownx.details

plugins:
    - search
    - awesome-pages

extra_javascript:
    - 'https://cdn.jsdelivr.net/gh/ireade/caniuse-embed/caniuse-embed.min.js'
